# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

SECRET_TOKEN: (use rake secret to generate this)
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
ROLES: [admin, editor, proofreader, tester, user, backer]
WORKFLOW_STATES: [proposed, draft, deferred, incomplete, edited, published, testing]
MEDIA_TYPES: [photo_interview, map_interview, interview_only, ambient_audio, text_only, text_with_photo, photo_gallery, map_static]
KYC_SEED_DATA_DEV: 
KYC_SEED_DATA_PROD: 
KYC_USER_JSON: kyc_users.json
KYC_ADMIN_USER_JSON: kyc_admin_users.json
KYC_COLLECTION_JSON: kyc_collection.json
KYC_THEMES_JSON: kyc_themes.json
KYC_GUESTS_JSON: kyc_guests.json
KYC_STORIES_JSON: kyc_story_from_log130624.json
KYC_TIDBITS_JSON: kyc-tidbits130603.json
WORKFLOW_STATE_TO_DISPLAY: 2
KYC_STATIC_ASSETS_URL: http://kycstatic.elsewiseapps.com/assets/
KYC_STATIC_AUDIO_URL: http://kycstatic.elsewiseapps.com/audio/
KYC_STATIC_PHOTOS_URL: http://kycstatic.elsewiseapps.com/assets/
WEBSITE_NAME: PDX Social History Guide