require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TidbitsController do

  # This should return the minimal set of attributes required to create a valid
  # Tidbit. As you add validations to Tidbit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TidbitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tidbits as @tidbits" do
      tidbit = Tidbit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tidbits).should eq([tidbit])
    end
  end

  describe "GET show" do
    it "assigns the requested tidbit as @tidbit" do
      tidbit = Tidbit.create! valid_attributes
      get :show, {:id => tidbit.to_param}, valid_session
      assigns(:tidbit).should eq(tidbit)
    end
  end

  describe "GET new" do
    it "assigns a new tidbit as @tidbit" do
      get :new, {}, valid_session
      assigns(:tidbit).should be_a_new(Tidbit)
    end
  end

  describe "GET edit" do
    it "assigns the requested tidbit as @tidbit" do
      tidbit = Tidbit.create! valid_attributes
      get :edit, {:id => tidbit.to_param}, valid_session
      assigns(:tidbit).should eq(tidbit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tidbit" do
        expect {
          post :create, {:tidbit => valid_attributes}, valid_session
        }.to change(Tidbit, :count).by(1)
      end

      it "assigns a newly created tidbit as @tidbit" do
        post :create, {:tidbit => valid_attributes}, valid_session
        assigns(:tidbit).should be_a(Tidbit)
        assigns(:tidbit).should be_persisted
      end

      it "redirects to the created tidbit" do
        post :create, {:tidbit => valid_attributes}, valid_session
        response.should redirect_to(Tidbit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tidbit as @tidbit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tidbit.any_instance.stub(:save).and_return(false)
        post :create, {:tidbit => { "title" => "invalid value" }}, valid_session
        assigns(:tidbit).should be_a_new(Tidbit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tidbit.any_instance.stub(:save).and_return(false)
        post :create, {:tidbit => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tidbit" do
        tidbit = Tidbit.create! valid_attributes
        # Assuming there are no other tidbits in the database, this
        # specifies that the Tidbit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tidbit.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => tidbit.to_param, :tidbit => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested tidbit as @tidbit" do
        tidbit = Tidbit.create! valid_attributes
        put :update, {:id => tidbit.to_param, :tidbit => valid_attributes}, valid_session
        assigns(:tidbit).should eq(tidbit)
      end

      it "redirects to the tidbit" do
        tidbit = Tidbit.create! valid_attributes
        put :update, {:id => tidbit.to_param, :tidbit => valid_attributes}, valid_session
        response.should redirect_to(tidbit)
      end
    end

    describe "with invalid params" do
      it "assigns the tidbit as @tidbit" do
        tidbit = Tidbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tidbit.any_instance.stub(:save).and_return(false)
        put :update, {:id => tidbit.to_param, :tidbit => { "title" => "invalid value" }}, valid_session
        assigns(:tidbit).should eq(tidbit)
      end

      it "re-renders the 'edit' template" do
        tidbit = Tidbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tidbit.any_instance.stub(:save).and_return(false)
        put :update, {:id => tidbit.to_param, :tidbit => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tidbit" do
      tidbit = Tidbit.create! valid_attributes
      expect {
        delete :destroy, {:id => tidbit.to_param}, valid_session
      }.to change(Tidbit, :count).by(-1)
    end

    it "redirects to the tidbits list" do
      tidbit = Tidbit.create! valid_attributes
      delete :destroy, {:id => tidbit.to_param}, valid_session
      response.should redirect_to(tidbits_url)
    end
  end

end
